"""Render the human-vs-cognitive-model comparison as one self-contained page.

Reads ``assets/human_vs_model_plot_data.json`` and writes
``assets/human_vs_model_report.html`` with the data inlined, so the file can be
served or opened directly with no network access and no build step.

This is a thin CLI over :func:`src.result_visualizer.render_comparison_report` --
the estimator and the page itself live in ``src`` so the same report is reachable
from the API via ``xaikitTest.render_human_vs_model_report``.

Run ``assets/build_human_vs_model_plot_data.py`` first.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

DATA = REPO_ROOT / "assets" / "human_vs_model_plot_data.json"
OUTPUT = REPO_ROOT / "assets" / "human_vs_model_report.html"

FOOTER = (
    "Generated by <code>assets/build_human_vs_model_report.py</code> from "
    "<code>assets/human_vs_model_plot_data.json</code>. "
    "No participant identifiers are present."
)


def main() -> int:
    from src.result_visualizer import ComparisonPanel, ComparisonStudy, render_comparison_report

    if not DATA.is_file():
        raise FileNotFoundError(
            f"{DATA.relative_to(REPO_ROOT)} not found. "
            "Run assets/build_human_vs_model_plot_data.py first."
        )
    payload = json.loads(DATA.read_text())
    studies = [
        ComparisonStudy(
            name=study["name"],
            task=study.get("task", ""),
            participants=study.get("participants"),
            panels=[ComparisonPanel(**panel) for panel in study["panels"]],
        )
        for study in payload["studies"]
    ]
    written = [
        (
            render_comparison_report(
                studies, OUTPUT, title="Human vs cognitive model", footer=FOOTER
            ),
            sum(len(study.panels) for study in studies),
        )
    ]
    # One page per cognitive model as well, so a UI can embed just the one it is
    # showing rather than the whole comparison.
    for study in studies:
        slug = study.name.lower().replace(" ", "_")
        written.append(
            (
                render_comparison_report(
                    [study],
                    OUTPUT.with_name(f"human_vs_model_{slug}.html"),
                    title=f"Human vs {study.name}",
                    footer=FOOTER,
                ),
                len(study.panels),
            )
        )

    for path, panels in written:
        print(
            f"  {str(path.relative_to(REPO_ROOT)):46s} {panels:2d} panels  "
            f"{path.stat().st_size:,} bytes"
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
