"""
XAI adapter API layer.

This layer wraps external attribution libraries such as Captum, LIME, SHAP,
and sklearn-style feature importance behind a consistent adapter interface.
"""

from .base import (
    XAIAdapter,
    XAIAdapterResult,
    baseline_from_data,
    ensure_2d,
    identity_postprocess,
    identity_preprocess,
    select_target,
)
from .api import (
    ExplanationRunConfig,
    combine_explanation_tables,
    create_coxam_xai_method,
    create_custom_surrogate_method,
    create_custom_xai_method,
    create_xai_method_from_engine,
    generate_surrogate_xai_methods,
    generate_sim2real_explanations,
    generate_xai_explanation_tables,
    get_coxam_xai_predictions,
    get_xai_methods_from_design,
    init_explanation_run,
    predict_labels,
)
from .attribution import (
    Attribution,
    CustomAttribution,
    DeepLift,
    GradientInput,
    IntegratedGradients,
    KernelShap,
    LeaveOneFeatureOut,
    Lime,
    LRPAdapter,
    ShapDeepExplainer,
    ShapGradientExplainer,
    ShapLinearExplainer,
    ShapTreeExplainer,
    Sim2RealPropertyAttribution,
    SklearnFeatureImportance,
    make_attribution,
)
from .concept import TCAVAdapter
from .dataset import CSVDatasetAdapter, PrecomputedCSVXAIMethod
from .example_based import CounterfactualAdapter, DiCEAdapter, PrototypesAdapter
from .interpret import EBMAdapter
from .registry import XAIAdapterRegistry, create_xai_method, get_adapter_registry, register_xai_method
from .surrogate import (
    AnchorsAdapter,
    CustomSurrogate,
    DecisionTreeSurrogateMethod,
    GeneratedSurrogateMethods,
    LogisticRegressionSurrogateMethod,
    RuleListSurrogateMethod,
    RuleSetSurrogateMethod,
    SurrogateMethod,
    extract_tree_rules,
    generate_decision_tree_table,
    generate_logistic_regression_table,
    generate_surrogate_tables,
    make_surrogate,
    rule_list_to_tree_structure,
)
from .visualization import (
    explanation_value_columns,
    plot_explanation_visual,
    plot_global_explanation_importance,
    plot_instance_explanation,
)

__all__ = [
    "XAIAdapter",
    "XAIAdapterResult",
    "baseline_from_data",
    "ensure_2d",
    "identity_postprocess",
    "identity_preprocess",
    "select_target",
    "ExplanationRunConfig",
    "combine_explanation_tables",
    "create_xai_method",
    "register_xai_method",
    "create_custom_xai_method",
    "create_custom_surrogate_method",
    "create_xai_method_from_engine",
    "create_coxam_xai_method",
    "generate_surrogate_xai_methods",
    "generate_sim2real_explanations",
    "generate_xai_explanation_tables",
    "get_coxam_xai_predictions",
    "get_xai_methods_from_design",
    "init_explanation_run",
    "predict_labels",
    "CSVDatasetAdapter",
    "PrecomputedCSVXAIMethod",
    "Attribution",
    "CustomAttribution",
    "make_attribution",
    "DeepLift",
    "GradientInput",
    "IntegratedGradients",
    "KernelShap",
    "LeaveOneFeatureOut",
    "Lime",
    "LRPAdapter",
    "ShapTreeExplainer",
    "ShapLinearExplainer",
    "ShapDeepExplainer",
    "ShapGradientExplainer",
    "Sim2RealPropertyAttribution",
    "SklearnFeatureImportance",
    "TCAVAdapter",
    "CounterfactualAdapter",
    "DiCEAdapter",
    "PrototypesAdapter",
    "AnchorsAdapter",
    "CustomSurrogate",
    "make_surrogate",
    "DecisionTreeSurrogateMethod",
    "LogisticRegressionSurrogateMethod",
    "RuleListSurrogateMethod",
    "RuleSetSurrogateMethod",
    "SurrogateMethod",
    "GeneratedSurrogateMethods",
    "extract_tree_rules",
    "generate_decision_tree_table",
    "generate_logistic_regression_table",
    "generate_surrogate_tables",
    "rule_list_to_tree_structure",
    "XAIAdapterRegistry",
    "get_adapter_registry",
    "EBMAdapter",
    "explanation_value_columns",
    "plot_explanation_visual",
    "plot_global_explanation_importance",
    "plot_instance_explanation",
]
